#ChipScope Core Inserter Project File Version 3.0
#Tue Apr 14 20:50:20 CEST 2026
Project.device.designInputFile=/home/user/_WORKSPACE_/kedziorno/ov7670_vga_Nexys2/top_cs.ngc
Project.device.designOutputFile=/home/user/_WORKSPACE_/kedziorno/ov7670_vga_Nexys2/top_cs.ngc
Project.device.deviceFamily=13
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/user/_WORKSPACE_/kedziorno/ov7670_vga_Nexys2/_ngo
Project.device.useSRL16=true
Project.filter.dimension=6
Project.filter<0>=*source_data*
Project.filter<1>=*dq*
Project.filter<2>=*clk*
Project.filter<3>=
Project.filter<4>=*ram*
Project.filter<5>=*ram_clk*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=inst_top_camera_monitoring crbc_i0 ram_clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=inst_top_camera_monitoring crbc_i0 source_data<0>
Project.unit<0>.dataChannel<10>=inst_top_camera_monitoring crbc_i0 source_data<10>
Project.unit<0>.dataChannel<11>=inst_top_camera_monitoring crbc_i0 source_data<11>
Project.unit<0>.dataChannel<12>=inst_top_camera_monitoring crbc_i0 source_data<12>
Project.unit<0>.dataChannel<13>=inst_top_camera_monitoring crbc_i0 source_data<13>
Project.unit<0>.dataChannel<14>=inst_top_camera_monitoring crbc_i0 source_data<14>
Project.unit<0>.dataChannel<15>=inst_top_camera_monitoring crbc_i0 source_data<15>
Project.unit<0>.dataChannel<1>=inst_top_camera_monitoring crbc_i0 source_data<1>
Project.unit<0>.dataChannel<2>=inst_top_camera_monitoring crbc_i0 source_data<2>
Project.unit<0>.dataChannel<3>=inst_top_camera_monitoring crbc_i0 source_data<3>
Project.unit<0>.dataChannel<4>=inst_top_camera_monitoring crbc_i0 source_data<4>
Project.unit<0>.dataChannel<5>=inst_top_camera_monitoring crbc_i0 source_data<5>
Project.unit<0>.dataChannel<6>=inst_top_camera_monitoring crbc_i0 source_data<6>
Project.unit<0>.dataChannel<7>=inst_top_camera_monitoring crbc_i0 source_data<7>
Project.unit<0>.dataChannel<8>=inst_top_camera_monitoring crbc_i0 source_data<8>
Project.unit<0>.dataChannel<9>=inst_top_camera_monitoring crbc_i0 source_data<9>
Project.unit<0>.dataDepth=8192
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=16
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=inst_top_camera_monitoring crbc_i0 source_data<0>
Project.unit<0>.triggerChannel<0><10>=inst_top_camera_monitoring crbc_i0 source_data<10>
Project.unit<0>.triggerChannel<0><11>=inst_top_camera_monitoring crbc_i0 source_data<11>
Project.unit<0>.triggerChannel<0><12>=inst_top_camera_monitoring crbc_i0 source_data<12>
Project.unit<0>.triggerChannel<0><13>=inst_top_camera_monitoring crbc_i0 source_data<13>
Project.unit<0>.triggerChannel<0><14>=inst_top_camera_monitoring crbc_i0 source_data<14>
Project.unit<0>.triggerChannel<0><15>=inst_top_camera_monitoring crbc_i0 source_data<15>
Project.unit<0>.triggerChannel<0><1>=inst_top_camera_monitoring crbc_i0 source_data<1>
Project.unit<0>.triggerChannel<0><2>=inst_top_camera_monitoring crbc_i0 source_data<2>
Project.unit<0>.triggerChannel<0><3>=inst_top_camera_monitoring crbc_i0 source_data<3>
Project.unit<0>.triggerChannel<0><4>=inst_top_camera_monitoring crbc_i0 source_data<4>
Project.unit<0>.triggerChannel<0><5>=inst_top_camera_monitoring crbc_i0 source_data<5>
Project.unit<0>.triggerChannel<0><6>=inst_top_camera_monitoring crbc_i0 source_data<6>
Project.unit<0>.triggerChannel<0><7>=inst_top_camera_monitoring crbc_i0 source_data<7>
Project.unit<0>.triggerChannel<0><8>=inst_top_camera_monitoring crbc_i0 source_data<8>
Project.unit<0>.triggerChannel<0><9>=inst_top_camera_monitoring crbc_i0 source_data<9>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=16
Project.unit<0>.triggerSequencerLevels=1
Project.unit<0>.triggerSequencerType=0
Project.unit<0>.type=ilapro
